language: lisp

env:
  matrix:
    - LISP=sbcl
    - LISP=ccl
    - LISP=clisp
    - LISP=ecl

install:
  - curl -L https://github.com/luismbo/cl-travis/raw/master/install.sh | sudo sh

script:
  - cl -e '(ql:quickload :lbot-test)
           (unless (prove:run :lbot-test)
              (uiop:quit 1))'
