language: lisp
sudo: required

env:
  matrix:
    - LISP=sbcl
    - LISP=ccl

install:
  - curl -L https://github.com/luismbo/cl-travis/raw/master/install.sh | sh

script:
  - cl -e '(push "." ql:*local-project-directories*)
           (ql:quickload :prove)
           (ql:quickload :lbot-test)
           (unless (prove:run :lbot-test)
              (uiop:quit 1))'
